export const SET_CURRENCY_RATES = 'SET_CURRENCY_RATES';
export const SET_LOADING = 'SET_LOADING';
export const SET_RATES_NAMES = 'SET_RATES_NAMES;'
export const SET_INTERVAL_UPDATA = 'SET_INTERVAL_UPDATA;'